//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:\PackageDev\OnionScript\src\OnionScript.Compiler\Grammar\OnionScript.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OrbHall.OnionScript.Compiler {

using System.Collections.Generic;

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class OnionScriptLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		WHITESPACE=25, STATEMENT_BEGIN=26, STATEMENT_END=27, STATEMENT_BEGIN_IGNORE_WHITESPACE=28, 
		STATEMENT_END_IGNORE_WHITESPACE=29, TEXT=30, BOOLEAN=31, FLOAT=32, INTEGER=33, 
		IDENTIFIER=34, COMMENT=35, ENDL=36;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "T__19", "T__20", "T__21", "T__22", "T__23", "UPPERCASE", 
		"LOWERCASE", "DIGIT", "HEXDIGIT", "ALPHACHAR", "ALPHANUMCHAR", "NEWLINE", 
		"WHITESPACE", "STATEMENT_BEGIN", "STATEMENT_END", "STATEMENT_BEGIN_IGNORE_WHITESPACE", 
		"STATEMENT_END_IGNORE_WHITESPACE", "TEXT", "BOOLEAN", "FLOAT", "INTEGER", 
		"IDENTIFIER", "COMMENT", "ENDL"
	};


	private Stack<bool> skipWhitespace = new Stack<bool>();


	public OnionScriptLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public OnionScriptLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'import'", "'func'", "'let'", "'return'", "'for'", "'while'", "'dowhile'", 
		"'='", "'+'", "'-'", "'*'", "'/'", "'%'", "'not'", "'and'", "'or'", "'nor'", 
		"'nand'", "'=='", "'!='", "'>'", "'>='", "'<'", "'<='", null, "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "WHITESPACE", "STATEMENT_BEGIN", "STATEMENT_END", "STATEMENT_BEGIN_IGNORE_WHITESPACE", 
		"STATEMENT_END_IGNORE_WHITESPACE", "TEXT", "BOOLEAN", "FLOAT", "INTEGER", 
		"IDENTIFIER", "COMMENT", "ENDL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "OnionScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static OnionScriptLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	public override void Action(RuleContext _localctx, int ruleIndex, int actionIndex) {
		switch (ruleIndex) {
		case 31 : WHITESPACE_action(_localctx, actionIndex); break;
		case 32 : STATEMENT_BEGIN_action(_localctx, actionIndex); break;
		case 33 : STATEMENT_END_action(_localctx, actionIndex); break;
		case 34 : STATEMENT_BEGIN_IGNORE_WHITESPACE_action(_localctx, actionIndex); break;
		case 35 : STATEMENT_END_IGNORE_WHITESPACE_action(_localctx, actionIndex); break;
		}
	}
	private void WHITESPACE_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 0:  if (skipWhitespace.Count == 0 || skipWhitespace.Peek()) Skip();  break;
		}
	}
	private void STATEMENT_BEGIN_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 1:  skipWhitespace.Push(false);  break;
		}
	}
	private void STATEMENT_END_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 2:  try { skipWhitespace.Pop(); } catch (InvalidOperationException) { }  break;
		}
	}
	private void STATEMENT_BEGIN_IGNORE_WHITESPACE_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 3:  skipWhitespace.Push(true);  break;
		}
	}
	private void STATEMENT_END_IGNORE_WHITESPACE_action(RuleContext _localctx, int actionIndex) {
		switch (actionIndex) {
		case 4:  try { skipWhitespace.Pop(); } catch (InvalidOperationException) { }  break;
		}
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '&', '\x13F', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x4', '+', '\t', '+', '\x4', ',', '\t', 
		',', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x5', '\x1D', '\xBA', 
		'\n', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x5', '\x1E', 
		'\xBF', '\n', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		'\x1F', '\x5', '\x1F', '\xC5', '\n', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', 
		' ', '\x5', ' ', '\xCA', '\n', ' ', '\x3', '!', '\x3', '!', '\x6', '!', 
		'\xCE', '\n', '!', '\r', '!', '\xE', '!', '\xCF', '\x3', '!', '\x3', '!', 
		'\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', 
		'#', '\x3', '$', '\x3', '$', '\a', '$', '\xDC', '\n', '$', '\f', '$', 
		'\xE', '$', '\xDF', '\v', '$', '\x3', '$', '\x3', '$', '\x3', '%', '\a', 
		'%', '\xE4', '\n', '%', '\f', '%', '\xE', '%', '\xE7', '\v', '%', '\x3', 
		'%', '\x3', '%', '\x3', '%', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', 
		'&', '\a', '&', '\xF0', '\n', '&', '\f', '&', '\xE', '&', '\xF3', '\v', 
		'&', '\x3', '&', '\x3', '&', '\x3', '\'', '\x3', '\'', '\x3', '\'', '\x3', 
		'\'', '\x3', '\'', '\x3', '\'', '\x3', '\'', '\x3', '\'', '\x3', '\'', 
		'\x5', '\'', '\x100', '\n', '\'', '\x3', '(', '\x5', '(', '\x103', '\n', 
		'(', '\x3', '(', '\x6', '(', '\x106', '\n', '(', '\r', '(', '\xE', '(', 
		'\x107', '\x5', '(', '\x10A', '\n', '(', '\x3', '(', '\x3', '(', '\x6', 
		'(', '\x10E', '\n', '(', '\r', '(', '\xE', '(', '\x10F', '\x5', '(', '\x112', 
		'\n', '(', '\x3', ')', '\x5', ')', '\x115', '\n', ')', '\x3', ')', '\x6', 
		')', '\x118', '\n', ')', '\r', ')', '\xE', ')', '\x119', '\x3', ')', '\x3', 
		')', '\x3', ')', '\x6', ')', '\x11F', '\n', ')', '\r', ')', '\xE', ')', 
		'\x120', '\x5', ')', '\x123', '\n', ')', '\x3', '*', '\x3', '*', '\x6', 
		'*', '\x127', '\n', '*', '\r', '*', '\xE', '*', '\x128', '\x5', '*', '\x12B', 
		'\n', '*', '\x3', '+', '\x3', '+', '\a', '+', '\x12F', '\n', '+', '\f', 
		'+', '\xE', '+', '\x132', '\v', '+', '\x3', '+', '\x6', '+', '\x135', 
		'\n', '+', '\r', '+', '\xE', '+', '\x136', '\x3', '+', '\x3', '+', '\x3', 
		',', '\x6', ',', '\x13C', '\n', ',', '\r', ',', '\xE', ',', '\x13D', '\x4', 
		'\xF1', '\x130', '\x2', '-', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x2', '\x35', '\x2', '\x37', '\x2', '\x39', '\x2', ';', '\x2', '=', '\x2', 
		'?', '\x2', '\x41', '\x1B', '\x43', '\x1C', '\x45', '\x1D', 'G', '\x1E', 
		'I', '\x1F', 'K', ' ', 'M', '!', 'O', '\"', 'Q', '#', 'S', '$', 'U', '%', 
		'W', '&', '\x3', '\x2', '\b', '\x3', '\x2', '\x43', '\\', '\x3', '\x2', 
		'\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x32', ';', '\x43', 
		'H', '\x63', 'h', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x4', '\x2', 
		'Z', 'Z', 'z', 'z', '\x2', '\x152', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', '\x2', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'S', '\x3', '\x2', '\x2', '\x2', '\x2', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'W', '\x3', '\x2', '\x2', '\x2', '\x3', 'Y', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '`', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\t', 'i', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'p', '\x3', '\x2', '\x2', '\x2', '\r', 't', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'z', '\x3', '\x2', '\x2', '\x2', '\x11', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x84', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x86', '\x3', '\x2', '\x2', '\x2', '\x17', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x19', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '!', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '#', '\x99', '\x3', '\x2', '\x2', '\x2', '%', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\'', '\xA2', '\x3', '\x2', '\x2', '\x2', ')', '\xA5', '\x3', 
		'\x2', '\x2', '\x2', '+', '\xA8', '\x3', '\x2', '\x2', '\x2', '-', '\xAA', 
		'\x3', '\x2', '\x2', '\x2', '/', '\xAD', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\x33', '\xB2', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xB4', '\x3', '\x2', '\x2', '\x2', '\x37', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xB9', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '=', '\xC4', '\x3', '\x2', '\x2', 
		'\x2', '?', '\xC9', '\x3', '\x2', '\x2', '\x2', '\x41', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\xD3', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\xD6', '\x3', '\x2', '\x2', '\x2', 'G', '\xD9', '\x3', '\x2', '\x2', 
		'\x2', 'I', '\xE5', '\x3', '\x2', '\x2', '\x2', 'K', '\xEB', '\x3', '\x2', 
		'\x2', '\x2', 'M', '\xFF', '\x3', '\x2', '\x2', '\x2', 'O', '\x102', '\x3', 
		'\x2', '\x2', '\x2', 'Q', '\x114', '\x3', '\x2', '\x2', '\x2', 'S', '\x124', 
		'\x3', '\x2', '\x2', '\x2', 'U', '\x12C', '\x3', '\x2', '\x2', '\x2', 
		'W', '\x13B', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', 'k', '\x2', 
		'\x2', 'Z', '[', '\a', 'o', '\x2', '\x2', '[', '\\', '\a', 'r', '\x2', 
		'\x2', '\\', ']', '\a', 'q', '\x2', '\x2', ']', '^', '\a', 't', '\x2', 
		'\x2', '^', '_', '\a', 'v', '\x2', '\x2', '_', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\a', 'h', '\x2', '\x2', '\x61', '\x62', '\a', 'w', 
		'\x2', '\x2', '\x62', '\x63', '\a', 'p', '\x2', '\x2', '\x63', '\x64', 
		'\a', '\x65', '\x2', '\x2', '\x64', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x65', '\x66', '\a', 'n', '\x2', '\x2', '\x66', 'g', '\a', 'g', '\x2', 
		'\x2', 'g', 'h', '\a', 'v', '\x2', '\x2', 'h', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\a', 't', '\x2', '\x2', 'j', 'k', '\a', 'g', '\x2', 
		'\x2', 'k', 'l', '\a', 'v', '\x2', '\x2', 'l', 'm', '\a', 'w', '\x2', 
		'\x2', 'm', 'n', '\a', 't', '\x2', '\x2', 'n', 'o', '\a', 'p', '\x2', 
		'\x2', 'o', '\n', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', 'h', '\x2', 
		'\x2', 'q', 'r', '\a', 'q', '\x2', '\x2', 'r', 's', '\a', 't', '\x2', 
		'\x2', 's', '\f', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 'y', '\x2', 
		'\x2', 'u', 'v', '\a', 'j', '\x2', '\x2', 'v', 'w', '\a', 'k', '\x2', 
		'\x2', 'w', 'x', '\a', 'n', '\x2', '\x2', 'x', 'y', '\a', 'g', '\x2', 
		'\x2', 'y', '\xE', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '\x66', 
		'\x2', '\x2', '{', '|', '\a', 'q', '\x2', '\x2', '|', '}', '\a', 'y', 
		'\x2', '\x2', '}', '~', '\a', 'j', '\x2', '\x2', '~', '\x7F', '\a', 'k', 
		'\x2', '\x2', '\x7F', '\x80', '\a', 'n', '\x2', '\x2', '\x80', '\x81', 
		'\a', 'g', '\x2', '\x2', '\x81', '\x10', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', '?', '\x2', '\x2', '\x83', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x85', '\a', '-', '\x2', '\x2', '\x85', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', '/', '\x2', '\x2', '\x87', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', ',', '\x2', 
		'\x2', '\x89', '\x18', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', 
		'\x31', '\x2', '\x2', '\x8B', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', '\'', '\x2', '\x2', '\x8D', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', 'p', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'q', '\x2', '\x2', '\x90', '\x91', '\a', 'v', '\x2', '\x2', '\x91', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', '\x63', '\x2', '\x2', 
		'\x93', '\x94', '\a', 'p', '\x2', '\x2', '\x94', '\x95', '\a', '\x66', 
		'\x2', '\x2', '\x95', ' ', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', 
		'\a', 'q', '\x2', '\x2', '\x97', '\x98', '\a', 't', '\x2', '\x2', '\x98', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', 'p', '\x2', '\x2', 
		'\x9A', '\x9B', '\a', 'q', '\x2', '\x2', '\x9B', '\x9C', '\a', 't', '\x2', 
		'\x2', '\x9C', '$', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', 
		'p', '\x2', '\x2', '\x9E', '\x9F', '\a', '\x63', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', 'p', '\x2', '\x2', '\xA0', '\xA1', '\a', '\x66', '\x2', 
		'\x2', '\xA1', '&', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', 
		'?', '\x2', '\x2', '\xA3', '\xA4', '\a', '?', '\x2', '\x2', '\xA4', '(', 
		'\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', '#', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', '?', '\x2', '\x2', '\xA7', '*', '\x3', '\x2', '\x2', '\x2', 
		'\xA8', '\xA9', '\a', '@', '\x2', '\x2', '\xA9', ',', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xAB', '\a', '@', '\x2', '\x2', '\xAB', '\xAC', '\a', 
		'?', '\x2', '\x2', '\xAC', '.', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', 
		'\a', '>', '\x2', '\x2', '\xAE', '\x30', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB0', '\a', '>', '\x2', '\x2', '\xB0', '\xB1', '\a', '?', '\x2', '\x2', 
		'\xB1', '\x32', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\t', '\x2', 
		'\x2', '\x2', '\xB3', '\x34', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', 
		'\t', '\x3', '\x2', '\x2', '\xB5', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\xB6', '\xB7', '\t', '\x4', '\x2', '\x2', '\xB7', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '\xB8', '\xBA', '\t', '\x5', '\x2', '\x2', '\xB9', '\xB8', 
		'\x3', '\x2', '\x2', '\x2', '\xBA', ':', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBF', '\x5', '\x33', '\x1A', '\x2', '\xBC', '\xBF', '\x5', '\x35', '\x1B', 
		'\x2', '\xBD', '\xBF', '\a', '\x61', '\x2', '\x2', '\xBE', '\xBB', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\xBD', '\x3', '\x2', '\x2', '\x2', '\xBF', '<', '\x3', '\x2', '\x2', 
		'\x2', '\xC0', '\xC5', '\x5', '\x33', '\x1A', '\x2', '\xC1', '\xC5', '\x5', 
		'\x35', '\x1B', '\x2', '\xC2', '\xC5', '\a', '\x61', '\x2', '\x2', '\xC3', 
		'\xC5', '\x5', '\x37', '\x1C', '\x2', '\xC4', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC2', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', 
		'>', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\a', '\xF', '\x2', '\x2', 
		'\xC7', '\xCA', '\a', '\f', '\x2', '\x2', '\xC8', '\xCA', '\a', '\f', 
		'\x2', '\x2', '\xC9', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', '\xCA', '@', '\x3', '\x2', '\x2', '\x2', '\xCB', 
		'\xCE', '\x5', '?', ' ', '\x2', '\xCC', '\xCE', '\t', '\x6', '\x2', '\x2', 
		'\xCD', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCC', '\x3', '\x2', 
		'\x2', '\x2', '\xCE', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xCD', 
		'\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', '\x2', '\x2', '\x2', 
		'\xD0', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', '\b', '!', 
		'\x2', '\x2', '\xD2', '\x42', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', 
		'\a', '*', '\x2', '\x2', '\xD4', '\xD5', '\b', '\"', '\x3', '\x2', '\xD5', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\a', '+', '\x2', 
		'\x2', '\xD7', '\xD8', '\b', '#', '\x4', '\x2', '\xD8', '\x46', '\x3', 
		'\x2', '\x2', '\x2', '\xD9', '\xDD', '\a', '*', '\x2', '\x2', '\xDA', 
		'\xDC', '\x5', '\x41', '!', '\x2', '\xDB', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDB', '\x3', 
		'\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xE0', '\xE1', '\b', '$', '\x5', '\x2', '\xE1', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\xE2', '\xE4', '\x5', '\x41', '!', '\x2', '\xE3', '\xE2', 
		'\x3', '\x2', '\x2', '\x2', '\xE4', '\xE7', '\x3', '\x2', '\x2', '\x2', 
		'\xE5', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE6', '\x3', '\x2', 
		'\x2', '\x2', '\xE6', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE5', 
		'\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\a', '+', '\x2', '\x2', '\xE9', 
		'\xEA', '\b', '%', '\x6', '\x2', '\xEA', 'J', '\x3', '\x2', '\x2', '\x2', 
		'\xEB', '\xF1', '\a', '$', '\x2', '\x2', '\xEC', '\xED', '\a', '^', '\x2', 
		'\x2', '\xED', '\xF0', '\a', '$', '\x2', '\x2', '\xEE', '\xF0', '\v', 
		'\x2', '\x2', '\x2', '\xEF', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEF', 
		'\xEE', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF3', '\x3', '\x2', '\x2', 
		'\x2', '\xF1', '\xF2', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xEF', '\x3', 
		'\x2', '\x2', '\x2', '\xF2', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF3', 
		'\xF1', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF5', '\a', '$', '\x2', 
		'\x2', '\xF5', 'L', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', '\a', 
		'v', '\x2', '\x2', '\xF7', '\xF8', '\a', 't', '\x2', '\x2', '\xF8', '\xF9', 
		'\a', 'w', '\x2', '\x2', '\xF9', '\x100', '\a', 'g', '\x2', '\x2', '\xFA', 
		'\xFB', '\a', 'h', '\x2', '\x2', '\xFB', '\xFC', '\a', '\x63', '\x2', 
		'\x2', '\xFC', '\xFD', '\a', 'n', '\x2', '\x2', '\xFD', '\xFE', '\a', 
		'u', '\x2', '\x2', '\xFE', '\x100', '\a', 'g', '\x2', '\x2', '\xFF', '\xF6', 
		'\x3', '\x2', '\x2', '\x2', '\xFF', '\xFA', '\x3', '\x2', '\x2', '\x2', 
		'\x100', 'N', '\x3', '\x2', '\x2', '\x2', '\x101', '\x103', '\a', '/', 
		'\x2', '\x2', '\x102', '\x101', '\x3', '\x2', '\x2', '\x2', '\x102', '\x103', 
		'\x3', '\x2', '\x2', '\x2', '\x103', '\x109', '\x3', '\x2', '\x2', '\x2', 
		'\x104', '\x106', '\x5', '\x37', '\x1C', '\x2', '\x105', '\x104', '\x3', 
		'\x2', '\x2', '\x2', '\x106', '\x107', '\x3', '\x2', '\x2', '\x2', '\x107', 
		'\x105', '\x3', '\x2', '\x2', '\x2', '\x107', '\x108', '\x3', '\x2', '\x2', 
		'\x2', '\x108', '\x10A', '\x3', '\x2', '\x2', '\x2', '\x109', '\x105', 
		'\x3', '\x2', '\x2', '\x2', '\x109', '\x10A', '\x3', '\x2', '\x2', '\x2', 
		'\x10A', '\x10B', '\x3', '\x2', '\x2', '\x2', '\x10B', '\x111', '\a', 
		'\x30', '\x2', '\x2', '\x10C', '\x10E', '\x5', '\x37', '\x1C', '\x2', 
		'\x10D', '\x10C', '\x3', '\x2', '\x2', '\x2', '\x10E', '\x10F', '\x3', 
		'\x2', '\x2', '\x2', '\x10F', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x10F', 
		'\x110', '\x3', '\x2', '\x2', '\x2', '\x110', '\x112', '\x3', '\x2', '\x2', 
		'\x2', '\x111', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x111', '\x112', 
		'\x3', '\x2', '\x2', '\x2', '\x112', 'P', '\x3', '\x2', '\x2', '\x2', 
		'\x113', '\x115', '\a', '/', '\x2', '\x2', '\x114', '\x113', '\x3', '\x2', 
		'\x2', '\x2', '\x114', '\x115', '\x3', '\x2', '\x2', '\x2', '\x115', '\x122', 
		'\x3', '\x2', '\x2', '\x2', '\x116', '\x118', '\x5', '\x37', '\x1C', '\x2', 
		'\x117', '\x116', '\x3', '\x2', '\x2', '\x2', '\x118', '\x119', '\x3', 
		'\x2', '\x2', '\x2', '\x119', '\x117', '\x3', '\x2', '\x2', '\x2', '\x119', 
		'\x11A', '\x3', '\x2', '\x2', '\x2', '\x11A', '\x123', '\x3', '\x2', '\x2', 
		'\x2', '\x11B', '\x11C', '\a', '\x32', '\x2', '\x2', '\x11C', '\x11E', 
		'\t', '\a', '\x2', '\x2', '\x11D', '\x11F', '\x5', '\x39', '\x1D', '\x2', 
		'\x11E', '\x11D', '\x3', '\x2', '\x2', '\x2', '\x11F', '\x120', '\x3', 
		'\x2', '\x2', '\x2', '\x120', '\x11E', '\x3', '\x2', '\x2', '\x2', '\x120', 
		'\x121', '\x3', '\x2', '\x2', '\x2', '\x121', '\x123', '\x3', '\x2', '\x2', 
		'\x2', '\x122', '\x117', '\x3', '\x2', '\x2', '\x2', '\x122', '\x11B', 
		'\x3', '\x2', '\x2', '\x2', '\x123', 'R', '\x3', '\x2', '\x2', '\x2', 
		'\x124', '\x12A', '\x5', ';', '\x1E', '\x2', '\x125', '\x127', '\x5', 
		'=', '\x1F', '\x2', '\x126', '\x125', '\x3', '\x2', '\x2', '\x2', '\x127', 
		'\x128', '\x3', '\x2', '\x2', '\x2', '\x128', '\x126', '\x3', '\x2', '\x2', 
		'\x2', '\x128', '\x129', '\x3', '\x2', '\x2', '\x2', '\x129', '\x12B', 
		'\x3', '\x2', '\x2', '\x2', '\x12A', '\x126', '\x3', '\x2', '\x2', '\x2', 
		'\x12A', '\x12B', '\x3', '\x2', '\x2', '\x2', '\x12B', 'T', '\x3', '\x2', 
		'\x2', '\x2', '\x12C', '\x130', '\a', '%', '\x2', '\x2', '\x12D', '\x12F', 
		'\v', '\x2', '\x2', '\x2', '\x12E', '\x12D', '\x3', '\x2', '\x2', '\x2', 
		'\x12F', '\x132', '\x3', '\x2', '\x2', '\x2', '\x130', '\x131', '\x3', 
		'\x2', '\x2', '\x2', '\x130', '\x12E', '\x3', '\x2', '\x2', '\x2', '\x131', 
		'\x134', '\x3', '\x2', '\x2', '\x2', '\x132', '\x130', '\x3', '\x2', '\x2', 
		'\x2', '\x133', '\x135', '\x5', '?', ' ', '\x2', '\x134', '\x133', '\x3', 
		'\x2', '\x2', '\x2', '\x135', '\x136', '\x3', '\x2', '\x2', '\x2', '\x136', 
		'\x134', '\x3', '\x2', '\x2', '\x2', '\x136', '\x137', '\x3', '\x2', '\x2', 
		'\x2', '\x137', '\x138', '\x3', '\x2', '\x2', '\x2', '\x138', '\x139', 
		'\b', '+', '\a', '\x2', '\x139', 'V', '\x3', '\x2', '\x2', '\x2', '\x13A', 
		'\x13C', '\x5', '?', ' ', '\x2', '\x13B', '\x13A', '\x3', '\x2', '\x2', 
		'\x2', '\x13C', '\x13D', '\x3', '\x2', '\x2', '\x2', '\x13D', '\x13B', 
		'\x3', '\x2', '\x2', '\x2', '\x13D', '\x13E', '\x3', '\x2', '\x2', '\x2', 
		'\x13E', 'X', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x2', '\xB9', '\xBE', 
		'\xC4', '\xC9', '\xCD', '\xCF', '\xDD', '\xE5', '\xEF', '\xF1', '\xFF', 
		'\x102', '\x107', '\x109', '\x10F', '\x111', '\x114', '\x119', '\x120', 
		'\x122', '\x128', '\x12A', '\x130', '\x136', '\x13D', '\b', '\x3', '!', 
		'\x2', '\x3', '\"', '\x3', '\x3', '#', '\x4', '\x3', '$', '\x5', '\x3', 
		'%', '\x6', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace OrbHall.OnionScript.Compiler
